### ISSUE TITLE
Request: Global hotkey to enable / disable the framerate cap

### ISSUE THREAD

**Issue by FitterSpace** [SuiMachine/Quantum-of-Solace-Tool#2]
There are some parts of the game that are framerate dependent, so it would be nice to have an option to disable the framerate cap with the press of a button instead of having to tab out and disable it manually, then enable it again later. The main reason I care is because when speedrunning this game, it can be a little annoying to tab out in the parts like the train level where the quick time events can kill you at framerates higher than 30.

**Comment by vrpixel** [comment]
It's more than naive to think anyone have interest in the game, especially when it's no longer sold for many many years...

**Comment by FitterSpace** [comment]
Why even bother posting a ridiculous comment like that. I don't care one bit what you think other people are interested in when you're not the person I'm asking about this. If you have nothing to contribute then don't waste your time commenting about it.

**Comment by vrpixel** [comment]
Then why do you comment back when you have nothing interesting to add?
You have obscure hobby for even more obscure game, take the source code and do the work. We will all appreciate it.

**Comment by FitterSpace** [comment]
Is that why this tool was made? Because SuiMachine expected a ton of people to use it for years and years? How are you going to say that nobody would care when you're the one replying to a random github message within 10 minutes of it being posted? I'll never understand the point of leaving a useless reply to a random forum post on github if you're not at all interested in what it's about.

**Comment by SuiMachine** [comment]
Because:
a - Was bored at that time and wanted to push myself
b - Was annoyed that there isn't an easy way to run this game in widescreen and set FOV.

Can't promise anything nowadays. During the week I have very little time working as a game developer. But if you can get me some map names and clips where that happens I will still try to have a look if something can be done about it.

**Comment by SuiMachine** [comment]
> It's more than naive to think anyone have interest in the game, especially when it's no longer sold for many many years...

It's on GOG. That was part of a motivation to even try and do something about it.

**Comment by SuiMachine** [comment]
Oh god, I didn't read the title. Yeah, i guess a cap by pressing a key shouldn't be too hard to implement.

**Comment by FitterSpace** [comment]
Thank you, SuiMachine. I really appreciate your response. Also, thanks for making this tool. It's crazy that they didn't have these options in the game, but you came along and fixed that.

**Comment by vrpixel** [comment]
I would say "nobody cares", cause fps hack was achieved shortly after the game released. This just looks like a self-made attempt to do the same.
And I can't find the game on GOG. Can you link it please?

**Comment by SuiMachine** [comment]
> I would say "nobody cares", cause fps hack was achieved shortly after the game released. This just looks like a self-made attempt to do the same.
> And I can't find the game on GOG. Can you link it please?

https://www.gog.com/game/soldier_of_fortune_ii_double_helix_gold_edition
Might not be available in all regions.

**Comment by SuiMachine** [comment]
Fuck that. My brain isn't working today apparently. Too many projects.

**Comment by SuiMachine** [comment]
Yeah, Quantum of Solace is not available for sale - Activision lost rights to use the IP, and MGM is a terrible corporation pretty much drove James Bond to the ground.

**Comment by FitterSpace** [comment]
It's okay, don't beat yourself up over it. It's true, the game isn't being sold anymore except through third-party retailers. I don't think that really matters, though. I'm not going to speak for anybody else but I've written scripts for other 007 games and I didn't consider for one second how popular the games were or whether or not they are still being sold. I'm pretty sure nobody has even used my scripts, but they're there in case anybody needs them. Making them is a fun challenge and it's something I enjoyed, so that's why I did it.

If you want to add a new feature to your tool, that's great. If not, that's fine, too. I appreciate your consideration either way.

**Comment by SuiMachine** [comment]
> It's okay, don't beat yourself up over it. It's true, the game isn't being sold anymore except through third-party retailers. I don't think that really matters, though. I'm not going to speak for anybody else but I've written scripts for other 007 games and I didn't consider for one second how popular the games were or whether or not they are still being sold. I'm pretty sure nobody has even used my scripts, but they're there in case anybody needs them. Making them is a fun challenge and it's something I enjoyed, so that's why I did it.
> 
> If you want to add a new feature to your tool, that's great. If not, that's fine, too. I appreciate your consideration either way.

I probably will. For whatever reason, I was thinking about Soldier of Fortune 2 (something with this issue 2). But yeah, since this is NOT SoF2 hack related (again, WTF brain - focus!) and just the trainer thing for Quantum of Solace, implementing a button to toggle it should be way easier.

**Comment by FitterSpace** [comment]
Thank you! I talked to some other people about it and there are other programs that can limit the fps with a keybind, but it would be nice to have it all in one program.

Unrelated, but I saw the stuff you put about this game on PCGamingWiki with all the memory addresses, it's insane the amount of work you've done for this game. There's a small but dedicated community around this game, and trust me, you've made a huge impact for us.

**Comment by SuiMachine** [comment]
https://github.com/SuiMachine/Quantum-of-Solace-Tool/commit/c0fa6f9c7688d443cf0e658a0990f2ef9de1a27c
https://github.com/SuiMachine/Quantum-of-Solace-Tool/releases/tag/1.3.0-Dev1

Will probably do more work on it tomorrow (will have to think about how I want to do rebindable key - mostly), when I can be bothered to install the game, but I think it should work.

**Comment by vrpixel** [comment]
I'll be damned. You pulled through.

**Comment by SuiMachine** [comment]
Closing, cause it's added now.
